### ISSUE TITLE
Setting up in Ubuntu 10.04

### ISSUE THREAD

**Issue by gonvaled** [Sleepingwell/DjangoRpyDemo#3]
To install django and r:

sudo pip install django
sudo apt-get install r-base-core

To solve problem locating shared library:

cd /usr/lib/
sudo ln -s /usr/lib/R/lib/libR.so .

**Comment by dzhibas** [comment]
and 
sudo pip install rpy2

**Comment by Sleepingwell** [comment]
Added these comments to README. Thanx again.
